--Observação de não colocar o codigos no sql de inserção

CREATE TABLE IF NOT EXISTS DISCIPLINAS(
    CODIGO_DISCIPLINA SERIAL PRIMARY KEY,
    NOME_DISCIPLINA VARCHAR(50) NOT NULL,
    CREDITOS_DISCIPLINA INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS PROFESSORES(
    CODIGO_PROFESSOR SERIAL PRIMARY KEY,
    NOME_PROFESSOR VARCHAR(100) NOT NULL,
    AREA_PESQUISA_PROFESSOR VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUNOS(
    MATRICULA_ALUNO SERIAL PRIMARY KEY,
    NOME_ALUNO VARCHAR(100) NOT NULL,
    SEMESTRE_ALUNO SMALLINT NOT NULL,
    DATA_NASCIMENTO_ALUNO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS TURMAS(
    CODIGO_TURMA SERIAL PRIMARY KEY,
    CODIGO_DISCIPLINA INTEGER,
    CODIGO_PROFESSOR INTEGER,
    ANO_TURMA VARCHAR(6) NOT NULL,
    HORARIO_TURMA VARCHAR(10) NOT NULL,

    CONSTRAINT FK_DISCIPLINA
        FOREIGN KEY (CODIGO_DISCIPLINA)
        REFERENCES DISCIPLINAS(CODIGO_DISCIPLINA)
    ON DELETE CASCADE,

    CONSTRAINT FK_PROFESSOR
        FOREIGN KEY (CODIGO_PROFESSOR)
        REFERENCES PROFESSORES(CODIGO_PROFESSOR)
    ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS HISTORICOS(
    CODIGO_HISTORICO SERIAL PRIMARY KEY,

    CODIGO_TURMA INTEGER NOT NULL,
    CODIGO_DISCIPLINA INTEGER NOT NULL,
    CODIGO_PROFESSOR INTEGER NOT NULL,
    MATRICULA_ALUNO INTEGER NOT NULL,

    ANO_HISTORICO VARCHAR(6) NOT NULL,
    FREQUENCIA_HISTORICO DECIMAL NOT NULL,
    NOTA_HISTORICO DECIMAL, -- Pode ser nulo, pode não haver nota ainda


    CONSTRAINT FK_TURMA
        FOREIGN KEY (CODIGO_TURMA)
        REFERENCES TURMAS(CODIGO_TURMA)
    ON DELETE CASCADE,

    CONSTRAINT FK_DISCIPLINA
        FOREIGN KEY (CODIGO_DISCIPLINA)
        REFERENCES DISCIPLINAS(CODIGO_DISCIPLINA)
    ON DELETE CASCADE,

    CONSTRAINT FK_PROFESSOR
        FOREIGN KEY (CODIGO_PROFESSOR)
        REFERENCES PROFESSORES(CODIGO_PROFESSOR)
    ON DELETE CASCADE,

    CONSTRAINT FK_ALUNO
        FOREIGN KEY (MATRICULA_ALUNO)
        REFERENCES ALUNOS(MATRICULA_ALUNO)
    ON DELETE CASCADE

);